# Generated by Django 6.0.2 on 2026-02-16 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='available', max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('environment', models.ForeignKey(db_column='environment_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='envs.environment')),
            ],
        ),
    ]
